### ISSUE TITLE
Authentication issues with bnc.ca

### ISSUE THREAD

**Issue by limb001** [duckduckgo/privacy-configuration#256]
We've had a number of breakage issues for users that have downloaded the latest version of the extension preventing login from working.

**Comment by SlayterDev** [comment]
Hello @limb001 can you confirm the issue is still happening today? We had some issues last week but currently the problematic feature should be disabled. If it is still happening can you confirm the issue persists if you turn off protections from the extension's dashboard? We'd love to help you get this resolved. Thanks!

**Comment by limb001** [comment]
Yes still having the issue.

**Comment by limb001** [comment]
Could you please Disable 'cookie' protection for api.bnc.ca and api2.bnc.ca?

**Comment by SlayterDev** [comment]
@limb001 We have released an update to the config which includes exceptions for the domains you listed. Please give 1-2hrs from this comment and let me know if the issue is fixed.

If it is not immediately fixed please trying disabling/re-enabling the extension in `chrome://extensions` or `about:addons` depending on your browser and trying again.

**Comment by GuiltyDolphin** [comment]
Thank you for reporting this issue. We are removing this mitigation and will monitor for further breakage.

If you find that users start to experience this breakage again, please encourage them to use the report flow provided in the extension. Don't hesitate to get in touch, and we'll be happy to investigate this further with you.
