### ISSUE TITLE
klaviyo.com breakage

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/privacy-configuration#362]
This issue outlines breakage for requests associated with the `klaviyo.com` domain.

- https://shopyalehome.com (last verified 2022-09-05)
  - site renders blank
  - requests required
    - `www.klaviyo.com/media/js/public/klaviyo_subscribe.js`
- https://fearofgod.com (last verified 2022-09-05)
  - site renders blank
  - requests required
    - `www.klaviyo.com/media/js/public/klaviyo_subscribe.js`

**Comment by sammacbeth** [comment]
Further `klaviyo.com` breakage:

- https://manage.kmail-lists.com/subscriptions/
  - site renders blank
  - requests required: https://static-app.klaviyo.com/fender/83919.401de5abb7927d48beb1.js

Root cause is missing entity data - kmail-lists.com and klaviyo.com share the same owner. This has been fixed in tracker-radar (https://github.com/duckduckgo/tracker-radar/pull/168) and will be resolved in the next blocklist update.

**Comment by chas-klaviyo** [comment]
Hi all, we have an additional issue that we opened up around this root issue: https://github.com/duckduckgo/privacy-configuration/issues/551 cc: @sammacbeth @GuiltyDolphin

**Comment by jdorweiler** [comment]
- https://footweartruth.com/  email signup form is missing

**Comment by shakyShane** [comment]
- email signup form missing from https://andieswim.com/en-gb/pages/fit-finder too

**Comment by dharb** [comment]
Additional Klaviyo breakage:
- https://github.com/duckduckgo/privacy-configuration/issues/1277 - kidsguide.com
- https://github.com/duckduckgo/privacy-configuration/pull/1748 - muc-off.com, paria.cc

**Comment by tagawa** [comment]
Email signup form missing on https://usafacts.org/signup/

**Comment by kzar** [comment]
Email signup form missing on https://holdonbags.com/

**Comment by kzar** [comment]
Email signup form missing on nestlenutritionstore.com

**Comment by kzar** [comment]
Email signup form missing on https://dreamfarm.com

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
