### ISSUE TITLE
crocs.com breakage

### ISSUE THREAD

**Issue by joshliebe** [duckduckgo/privacy-configuration#567]
- crocs.com (last verified 2022-12-06)
  - Site loads blank and does not proceed on Android.
  - Caused by fingerprinting hardware protection.

**Comment by jonathanKingston** [comment]
@joshliebe was there anything in the console at all? There's three protections in this setup seen here: https://github.com/duckduckgo/content-scope-scripts/blob/main/src/features/fingerprinting-hardware.js

- navigator.deviceMemory
- navigator.hardwareConcurrency
- navigator.keyboard

Perhaps the keyboard one is the issue here?

I don't think we have a way to disable this remotely in isolation due to the default of 'undefined' but haven't tested this theory. For example the site could be calling `navigator.keyboard.getLayoutMap()` due to the device looking more like a mobile.

**Comment by joshliebe** [comment]
@jonathanKingston I didn't see anything useful in the console... I also removed the keyboard one to check but it didn't have an effect. I also upped the RAM value to 8 (The amount that my test device has) and that didn't fix it either.

**Comment by laghee** [comment]
Closing out as **archived** since we updated to a new transparency system in PR #2137
